import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowRight, BadgeCheck, BrainCircuit, CalendarDays, CheckCircle2, Clock3, Code2, Edit3, Flame, Github, Layers3, Link, Linkedin, Save, ShieldCheck, Sparkles, Target, TrendingUp, Trophy, UserRound } from 'lucide-react';
import type { AuthUser } from './AuthModal';
import { apiUrl, safeStorage } from './apiConfig';

type PageTarget = 'studio' | 'assessment' | 'bank' | 'analytics';
type Props = { user: AuthUser | null; onNavigate: (page: PageTarget) => void; onRequireAuth: () => void; onUserUpdated: (user: AuthUser) => void };
const fallback = [{ date: 'JUL 03', star: 62, accuracy: 68, fillers: 9.2 }, { date: 'JUL 08', star: 66, accuracy: 71, fillers: 7.4 }, { date: 'JUL 14', star: 73, accuracy: 76, fillers: 5.6 }, { date: 'JUL 19', star: 77, accuracy: 79, fillers: 4.1 }, { date: 'JUL 26', star: 84, accuracy: 82, fillers: 3.2 }];
const profileFields = ['bio', 'linkedin', 'github', 'experience', 'projects'] as const;
type ProfileField = typeof profileFields[number];
const external = (value = '') => /^https?:\/\//i.test(value) ? value : value ? `https://${value}` : '#';
const skillMap = [{ label: 'Arrays & hashing', value: 78, tone: 'violet' }, { label: 'Trees & graphs', value: 64, tone: 'coral' }, { label: 'System design', value: 71, tone: 'mint' }, { label: 'Behavioral stories', value: 86, tone: 'ink' }];
const practiceRhythm = Array.from({ length: 70 }, (_, index) => (index * 17 + index * index * 3) % 7);

export function UserDashboard({ user, onNavigate, onRequireAuth, onUserUpdated }: Props) {
  const [data, setData] = useState(fallback); const [profile, setProfile] = useState<AuthUser | null>(user); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState('');
  useEffect(() => { fetch(apiUrl('/api/analytics')).then(response => response.json()).then(payload => setData(payload.sessions || fallback)).catch(() => undefined); }, []);
  useEffect(() => { const token = safeStorage.get('telos-token'); if (!token) return; fetch(apiUrl('/api/auth/me'), { headers: { Authorization: `Bearer ${token}` } }).then(response => response.ok ? response.json() : null).then(payload => { if (payload?.user) { setProfile(payload.user); onUserUpdated(payload.user); } }).catch(() => undefined); }, [onUserUpdated]);
  const latest = useMemo(() => data[data.length - 1] || fallback[fallback.length - 1], [data]);
  const candidate = profile || user; const firstName = candidate?.name.split(' ')[0] || 'Candidate';
  const gate = (page: PageTarget) => candidate ? onNavigate(page) : onRequireAuth();
  const update = (field: ProfileField, value: string) => setProfile(current => current ? { ...current, [field]: value } : current);
  const saveProfile = async () => { const token = safeStorage.get('telos-token'); if (!token || !profile) return; setSaving(true); setNotice(''); try { const response = await fetch(apiUrl('/api/auth/me'), { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(profile) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Could not save your profile.'); setProfile(payload.user); onUserUpdated(payload.user); setEditing(false); setNotice('Profile saved securely.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not save your profile.'); } finally { setSaving(false); } };
  const projects = candidate?.projects?.split('\n').filter(Boolean) || [];
  const completedFields = profileFields.filter(field => candidate?.[field]?.trim()).length; const completeness = Math.round((completedFields / profileFields.length) * 100);
  return <main className="shell dashboard-shell">
    <section className="dashboard-hero"><div><p className="kicker">PRIVATE CANDIDATE SPACE / TELOS</p><h1>Good to see you,<br/><i>{firstName}.</i></h1><p>Your secure profile, interview readiness, verified assessment work, and highest-leverage next steps—kept in one personal workspace.</p></div><article className="dashboard-readiness"><span><Sparkles size={15}/> READINESS INDEX</span><b>{latest.star}</b><strong>+14 this month</strong><small>Strongest lift: clearer technical reasoning and more controlled delivery.</small></article></section>
    <section className="dashboard-command"><div className="command-tabs"><button className="active"><Layers3 size={15}/> OVERVIEW</button><button onClick={() => gate('bank')}><Code2 size={15}/> PRACTICE LIBRARY</button><button onClick={() => gate('analytics')}><TrendingUp size={15}/> PERFORMANCE</button></div><div className="streak-chip"><Flame size={17}/><span><b>7 day streak</b><small>Best: 12 days</small></span><button onClick={() => gate('bank')}>KEEP IT GOING <ArrowRight size={14}/></button></div></section>
    <section className="candidate-profile"><div className="profile-card-head"><div><span className="profile-avatar">{firstName.slice(0, 1).toUpperCase()}</span><div><p className="kicker">YOUR CANDIDATE PROFILE</p><h2>{candidate?.name || 'Your name'}</h2><small>{candidate?.email}</small></div></div><button className="ghost-button" onClick={() => setEditing(value => !value)}><Edit3 size={14}/> {editing ? 'CANCEL EDIT' : 'EDIT PROFILE'}</button></div>
      {editing ? <div className="profile-form"><label>ABOUT YOU<textarea value={profile?.bio || ''} onChange={event => update('bio', event.target.value)} placeholder="A concise professional introduction, target role, and what you are working toward."/></label><div className="profile-form-grid"><label>LINKEDIN PROFILE<input value={profile?.linkedin || ''} onChange={event => update('linkedin', event.target.value)} placeholder="linkedin.com/in/your-name"/></label><label>GITHUB PROFILE<input value={profile?.github || ''} onChange={event => update('github', event.target.value)} placeholder="github.com/your-name"/></label></div><label>EXPERIENCE<textarea value={profile?.experience || ''} onChange={event => update('experience', event.target.value)} placeholder="Internships, jobs, achievements, technologies, and measurable outcomes."/></label><label>PROJECTS + REPOSITORY LINKS<textarea value={profile?.projects || ''} onChange={event => update('projects', event.target.value)} placeholder={'One project per line, e.g.\nInterviewCopilot — https://github.com/you/interview-copilot\nPayment API — https://github.com/you/payment-api'}/></label><div className="profile-save-row"><span>{notice}</span><button className="brand-button" disabled={saving} onClick={() => void saveProfile()}><Save size={15}/>{saving ? 'SAVING…' : 'SAVE PROFILE'}</button></div></div> : <div className="profile-view"><p>{candidate?.bio || 'Add a short bio so your interview preparation can stay aligned to your goals.'}</p><div className="profile-links">{candidate?.linkedin ? <a href={external(candidate.linkedin)} target="_blank" rel="noreferrer"><Linkedin size={15}/> LinkedIn profile</a> : <button type="button" onClick={() => setEditing(true)}><Linkedin size={15}/> Add LinkedIn</button>}{candidate?.github ? <a href={external(candidate.github)} target="_blank" rel="noreferrer"><Github size={15}/> GitHub profile</a> : <button type="button" onClick={() => setEditing(true)}><Github size={15}/> Add GitHub</button>}<span><UserRound size={15}/> {completeness}% profile complete</span></div><div className="profile-detail-grid"><article><p className="kicker">EXPERIENCE</p><span>{candidate?.experience || 'Add work experience, internships, achievements, and core technologies.'}</span></article><article><p className="kicker">PROJECT PORTFOLIO</p>{projects.length ? <ul>{projects.slice(0, 3).map(item => <li key={item}><Link size={13}/>{item}</li>)}</ul> : <span>Add projects and repository links to make your profile portfolio-ready.</span>}</article></div></div>}</section>
    <section className="dashboard-actions"><button onClick={() => gate('studio')}><BrainCircuit size={22}/><span><b>Practice interview</b><small>Continue your backend engineer mock</small></span><ArrowRight size={17}/></button><button onClick={() => gate('assessment')}><ShieldCheck size={22}/><span><b>Verified assessment</b><small>Start a company DSA screen</small></span><ArrowRight size={17}/></button><button onClick={() => gate('bank')}><Code2 size={22}/><span><b>Daily drill</b><small>Complete one timed coding problem</small></span><ArrowRight size={17}/></button></section>
    <section className="dashboard-grid"><article className="dashboard-chart"><div className="dashboard-card-head"><div><p className="kicker">LAST 30 DAYS</p><h2>Readiness trajectory</h2></div><button onClick={() => gate('analytics')}>OPEN ANALYTICS <ArrowRight size={14}/></button></div><ResponsiveContainer width="100%" height={255}><AreaChart data={data}><defs><linearGradient id="dashboardReadiness" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#6e54f6" stopOpacity=".5"/><stop offset="100%" stopColor="#6e54f6" stopOpacity=".02"/></linearGradient></defs><CartesianGrid stroke="#d9d7df" vertical={false}/><XAxis dataKey="date" tickLine={false} axisLine={false}/><YAxis domain={[50,100]} tickLine={false} axisLine={false}/><Tooltip/><Area type="monotone" dataKey="star" stroke="#6e54f6" fill="url(#dashboardReadiness)" strokeWidth={3}/></AreaChart></ResponsiveContainer></article><article className="dashboard-focus"><p className="kicker">THIS WEEK'S FOCUS</p><h2>Turn clarity into a repeatable habit.</h2><div className="focus-task"><span>01</span><p><b>Complete Google DSA screen</b><small>Five tasks • 75 min • proctored</small></p><button onClick={() => gate('assessment')}>START</button></div><div className="focus-task"><span>02</span><p><b>Explain one system trade-off</b><small>20 min speaking drill</small></p><button onClick={() => gate('studio')}>PRACTICE</button></div><div className="focus-task"><span>03</span><p><b>Re-solve one missed pattern</b><small>Arrays &amp; hashing</small></p><button onClick={() => gate('bank')}>DRILL</button></div></article></section>
    <section className="dashboard-insights"><article><Target size={18}/><p className="kicker">CURRENT SIGNAL</p><b>{latest.accuracy}%</b><span>Technical-answer accuracy</span></article><article><Clock3 size={18}/><p className="kicker">PACING</p><b>142 WPM</b><span>In the confident target range</span></article><article><TrendingUp size={18}/><p className="kicker">STRONGEST SKILL</p><b>Trade-offs</b><span>Clear system constraints and choices</span></article><article><BadgeCheck size={18}/><p className="kicker">PROFILE SIGNAL</p><b>{completeness}%</b><span>Candidate profile complete</span></article></section>
    <section className="dashboard-practice-grid"><article className="daily-challenge"><div><p className="kicker">TODAY'S INTERVIEW DRILL</p><span className="challenge-level">MEDIUM · 25 MIN</span><h2>Design a rate limiter for a public API.</h2><p>Explain the data model, one trade-off, and how you would keep the service reliable under a burst of traffic.</p><div className="challenge-tags"><span>System design</span><span>Scalability</span><span>Trade-offs</span></div></div><button className="black-button" onClick={() => gate('studio')}>START DRILL <ArrowRight size={16}/></button></article><article className="skill-map-card"><div className="dashboard-card-head"><div><p className="kicker">SKILL MAP</p><h2>Your practice coverage</h2></div><button onClick={() => gate('bank')}>VIEW DRILLS <ArrowRight size={14}/></button></div><div className="skill-map">{skillMap.map(skill => <div key={skill.label}><span><b>{skill.label}</b><small>{skill.value}%</small></span><i><em className={skill.tone} style={{ width: `${skill.value}%` }}/></i></div>)}</div></article></section>
    <section className="dashboard-growth-grid"><article className="rhythm-card"><div className="dashboard-card-head"><div><p className="kicker">CONSISTENCY</p><h2>Practice rhythm</h2></div><span className="rhythm-legend"><i/> active day</span></div><div className="rhythm-grid">{practiceRhythm.map((level, index) => <span key={index} className={`level-${level}`} title={`${level ? level : 'No'} practice blocks`}/>)}</div><div className="rhythm-footer"><span>10 weeks of practice</span><b>18 focused sessions</b></div></article><article className="achievement-card"><div><p className="kicker">LATEST MILESTONE</p><Trophy size={23}/><h2>Clear communicator</h2><p>Earned by structuring three answers with a decision, constraint, and measurable result.</p></div><button onClick={() => gate('analytics')}>VIEW ALL ACHIEVEMENTS <ArrowRight size={15}/></button></article><article className="next-unlock"><CheckCircle2 size={20}/><div><p className="kicker">NEXT UNLOCK</p><b>Complete 2 more company assessments</b><span>Unlock your verified readiness comparison.</span></div></article></section>
    <section className="dashboard-bottom"><article><div className="dashboard-card-head"><div><p className="kicker">RECENT ACTIVITY</p><h2>Your learning trail</h2></div><CalendarDays size={19}/></div><div className="activity-row"><span className="activity-dot violet"/><p><b>Interview readiness improved</b><small>STAR structure and delivery are trending upward.</small></p><time>Today</time></div><div className="activity-row"><span className="activity-dot coral"/><p><b>Company playbook saved</b><small>Google software engineering preparation plan.</small></p><time>Yesterday</time></div><div className="activity-row"><span className="activity-dot mint"/><p><b>New DSA drill recommended</b><small>Practice a graph traversal under time pressure.</small></p><time>2 days ago</time></div></article><article className="dashboard-note"><p className="kicker">COACH NOTE</p><h2>You're close to interview-ready.</h2><p>Your next improvement is consistency: narrate the invariant, test an edge case, then state the complexity before you finish.</p><button className="black-button" onClick={() => gate('studio')}>OPEN COACHING <ArrowRight size={16}/></button></article></section>
  </main>;
}
