export function calculateSpeakingPace(words: number, minutes: number): number {
  if (!minutes || minutes <= 0) return words > 0 ? Math.round(words * 60) : 0;
  return Math.round((words / minutes));
}

const FILLER_PATTERNS = /\b(um|uh|umm|uhh|like|basically|actually|you know|sort of|kind of|i mean)\b/gi;

export function countFillerWords(text: string): { count: number; fillers: Record<string, number> } {
  const matches = text.match(FILLER_PATTERNS) || [];
  const fillers: Record<string, number> = {};
  for (const m of matches) {
    const key = m.toLowerCase();
    fillers[key] = (fillers[key] || 0) + 1;
  }
  return { count: matches.length, fillers };
}

export function buildSessionReport({ answerCount, pace }: { answerCount: number; pace: number }) {
  const clarity = Math.min(95, 70 + answerCount * 5);
  const accuracy = Math.min(95, 74 + answerCount * 3);
  const paceScore = Math.min(180, 120 + Math.round(pace / 10));
  const rhythmScore = Math.min(95, 72 + Math.round((pace - 120) / 6));
  return { clarity, accuracy, paceScore, rhythmScore };
}

export function exportDebriefToMarkdown(debrief: any, context: { company?: string; role?: string; focus?: string }): string {
  if (!debrief) return '';
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const company = context.company || 'Tech Company';
  const role = context.role || 'Software Engineer';

  let md = `# TeLos Technical Interview Debrief & Scorecard\n\n`;
  md += `**Candidate Assessment for ${role} at ${company}**\n`;
  md += `*Date: ${now} | Evaluation Focus: ${context.focus || 'Systems & Architecture'}*\n\n`;
  md += `---\n\n`;

  md += `## 🏆 Executive Summary & Hiring Recommendation\n\n`;
  md += `**Recommendation:** \`${debrief.hiringRecommendation || 'Hire'}\`\n\n`;
  md += `**Rationale:** ${debrief.hiringRationale || debrief.summary || 'Strong performance across technical depth and problem-solving.'}\n\n`;

  if (debrief.scores) {
    md += `### Calibrated Scores\n`;
    md += `- **Overall Score:** ${debrief.scores.overall ?? 85}/100\n`;
    md += `- **Technical Depth:** ${debrief.scores.technicalDepth ?? 80}/100\n`;
    md += `- **Problem Solving:** ${debrief.scores.problemSolving ?? 85}/100\n`;
    md += `- **Communication & Trade-offs:** ${debrief.scores.communication ?? 88}/100\n\n`;
  }

  if (Array.isArray(debrief.questionsAnalysis) && debrief.questionsAnalysis.length > 0) {
    md += `## 💬 Question-by-Question Deep Dive ("What You Said" vs "What You Should Say")\n\n`;
    debrief.questionsAnalysis.forEach((q: any, idx: number) => {
      md += `### ${idx + 1}. ${q.question}\n\n`;
      md += `**Verdict:** \`${q.verdict || 'Adequate'}\`\n\n`;
      md += `**🗣️ What You Said:**\n> ${q.whatYouSaid || 'N/A'}\n\n`;
      md += `**✨ Ideal High-Bar Response (What You Should Say):**\n${q.whatYouShouldSay || 'N/A'}\n\n`;
      if (q.feedback) {
        md += `**💡 Concrete Feedback:** ${q.feedback}\n\n`;
      }
      md += `---\n\n`;
    });
  }

  if (Array.isArray(debrief.whatToImprove) && debrief.whatToImprove.length > 0) {
    md += `## 🛠️ Areas to Improve\n\n`;
    debrief.whatToImprove.forEach((item: any) => {
      md += `- **${item.title}:** ${item.detail}\n`;
      if (item.actionItem) md += `  - *Action Item:* ${item.actionItem}\n`;
    });
    md += `\n`;
  }

  if (Array.isArray(debrief.whatNotToSay) && debrief.whatNotToSay.length > 0) {
    md += `## 🚫 What NOT to Say (Anti-Patterns to Avoid)\n\n`;
    debrief.whatNotToSay.forEach((item: any) => {
      md += `- **Phrase/Habit:** *"${item.phraseOrHabit}"*\n`;
      md += `  - **Why to Avoid:** ${item.whyAvoid}\n`;
      md += `  - **Better Alternative:** ${item.betterAlternative}\n\n`;
    });
  }

  if (Array.isArray(debrief.whatYouImproved) && debrief.whatYouImproved.length > 0) {
    md += `## 🌟 Standout Strengths\n\n`;
    debrief.whatYouImproved.forEach((item: any) => {
      md += `- **${item.strength}:** ${item.observation}\n`;
    });
    md += `\n`;
  }

  md += `\n*Generated by TeLos AI Technical Interview Studio.*`;
  return md;
}
